#RunMlp_0.0.L.bash
#Author= Lucia
#Version= 0.0
#Date: 11/10/17
#Description: Bash to run all the combinations with the classifier 'MLP'
#Parameters: None
#Output: Reports, models and vectorizers for each combination

source activate python3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training-sentences.rs.lemma_postag_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_postag_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swTrue_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDF_swFalse_ng1-3.txt --classifier MLP --vectype TFIDF --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swTrue_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_BINARY_swFalse_ng1-3.txt --classifier MLP --vectype BINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swTrue_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords True --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
python3 /export/storage/users/luciarn/BI_project/Mineria/Codes/training-cross-validation-improving_1.0.FL.py --inputPath /export/storage/users/luciarn/BI_project/Mineria/Data --inputTrainingSentences training sentences.rs.lemma_rs_dis_kws.txt --inputTrainingClasses training-classes.txt --outputPath /export/storage/users/luciarn/BI_project/Mineria/Reports --outputFile report.MLP_lemma_rs_dis_kws_TFIDFBINARY_swFalse_ng1-3.txt --classifier MLP --vectype TFIDFBINARY --positiveClass DISEASE --removeStopWords False --sngram 1 --fngram 3 
